# Introduction
* **작성자**: 박소희
* **본 주피터 코드 목적**: GSE111016 RNA-seq의 DEG 분석을 위함
* **데이터셋**: GSE111016
* **데이터셋 설명**:
    * Experiment type: Expression profiling by high throughput sequencing
    * Platform: Illumina HiSeq 2500 (Homo sapiens)
    * Experiment molecule: total RNA
* **샘플 설명**:
    * 평균 70.2세 (control): 20명
    * 평균 72.7세 (sarcopenic): 20명
* **참고 논문**: https://www.nature.com/articles/s41467-019-13694-1  
* **데이터셋 링크**: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111016

# Load library

In [1]:
import pandas as pd

import pydeseq2
from pydeseq2.dds import DeseqDataSet
from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats
from pydeseq2.utils import load_example_data

import pickle
import os
os.chdir('/Users/soheepark/03-GEO근감소/Data/gse111016/')

# Data collection 
* DEG 분석을 위해 **Count table**과 샘플의 그룹 정보가 포함된 **Metadata**가 필요합니다.
* 아래에서 **Count table**과 **Metadata table**을 불러와 형태를 확인합니다.

먼저 **Count table을 확인**해봅니다.

In [2]:
# Count table 로드
counts = pd.read_csv('../2_GSE111016/GSE111016_allSamplesCounts_htseqcov1_sss_forGEO.csv', index_col=0)
print(counts.shape)
counts.head()

(65217, 40)

,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,...,Sample 31,Sample 32,Sample 33,Sample 34,Sample 35,Sample 36,Sample 37,Sample 38,Sample 39,Sample 40
ENSG00000000003,124,145,61,110,122,120,145,118,108,125,...,114,119,79,67,134,114,106,128,149,122
ENSG00000000005,7,6,10,16,124,9,37,3,6,45,...,70,3,6,35,5,16,8,6,27,18
ENSG00000000419,536,839,415,690,825,852,774,838,629,708,...,482,739,639,462,780,551,576,788,742,656
ENSG00000000457,402,538,244,486,538,549,629,525,430,453,...,389,405,431,292,494,443,395,551,483,438
ENSG00000000460,141,119,73,169,96,104,145,115,94,131,...,118,104,145,85,131,115,141,121,125,120

다음으로 **Metadata를 확인**해봅니다.

In [3]:
# Metadata 로드
meta = pd.read_csv('../2_GSE111016/GSE111016_series_matrix.txt', sep='\t', skiprows=37, index_col=0)
meta.head()

,Sample 1 [sss],Sample 2 [sss],Sample 3 [sss],Sample 4 [sss],Sample 5 [sss],Sample 6 [sss],Sample 7 [sss],Sample 8 [sss],Sample 9 [sss],Sample 10 [sss],...,Sample 31 [sss],Sample 32 [sss],Sample 33 [sss],Sample 34 [sss],Sample 35 [sss],Sample 36 [sss],Sample 37 [sss],Sample 38 [sss],Sample 39 [sss],Sample 40 [sss]
!Sample_title,,,,,,,,,,,,,,,,,,,,,
!Sample_geo_accession,GSM3020405,GSM3020406,GSM3020407,GSM3020408,GSM3020409,GSM3020410,GSM3020411,GSM3020412,GSM3020413,GSM3020414,...,GSM3020435,GSM3020436,GSM3020437,GSM3020438,GSM3020439,GSM3020440,GSM3020441,GSM3020442,GSM3020443,GSM3020444
!Sample_status,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,...,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019,Public on Nov 14 2019
!Sample_submission_date,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,...,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018,Feb 22 2018
!Sample_last_update_date,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,...,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019,Nov 14 2019
!Sample_type,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,...,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA,SRA

`!Sample_characteristics_ch1` 행에 **환자 그룹의 특징이 저장**되어 있습니다.

In [4]:
meta.loc['!Sample_characteristics_ch1']

,Sample 1 [sss],Sample 2 [sss],Sample 3 [sss],Sample 4 [sss],Sample 5 [sss],Sample 6 [sss],Sample 7 [sss],Sample 8 [sss],Sample 9 [sss],Sample 10 [sss],...,Sample 31 [sss],Sample 32 [sss],Sample 33 [sss],Sample 34 [sss],Sample 35 [sss],Sample 36 [sss],Sample 37 [sss],Sample 38 [sss],Sample 39 [sss],Sample 40 [sss]
!Sample_title,,,,,,,,,,,,,,,,,,,,,
!Sample_characteristics_ch1,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,...,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent
!Sample_characteristics_ch1,sarcopenia status: no,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: no,...,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes
!Sample_characteristics_ch1,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,...,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male
!Sample_characteristics_ch1,age (yr): 69,age (yr): 69,age (yr): 69,age (yr): 73,age (yr): 71,age (yr): 65,age (yr): 78,age (yr): 66,age (yr): 71,age (yr): 67,...,age (yr): 78,age (yr): 79,age (yr): 74,age (yr): 69,age (yr): 69,age (yr): 74,age (yr): 78,age (yr): 65,age (yr): 68,age (yr): 66
!Sample_characteristics_ch1,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,...,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle

`!Sample_characteristics_ch1` 행에서 **그룹 정보가 들어간 행**을 사용할겁니다.  
다음에서 개수를 확인해봅니다.

In [5]:
# 그룹 특징 추출 및 개수 파악
meta.iloc[9].value_counts()

sarcopenia status: no     20
sarcopenia status: yes    20
Name: !Sample_characteristics_ch1, dtype: int64

In [6]:
meta.iloc[9].head()

Sample 1 [sss]     sarcopenia status: no
Sample 2 [sss]     sarcopenia status: no
Sample 3 [sss]    sarcopenia status: yes
Sample 4 [sss]    sarcopenia status: yes
Sample 5 [sss]     sarcopenia status: no
Name: !Sample_characteristics_ch1, dtype: object

In [7]:
# 필요한 행만 추출
val1 = pd.Series(meta.columns).apply(lambda x:x.split(' [')[0])
val2 = meta.iloc[9].apply(lambda x:x.split(': ')[-1])

# no, yes -> oh(old health), os(old sarcopenia)
my_dict = {'no':'OH', 'yes':'OS'}
val2 = val2.map(my_dict)

metadata = dict(zip(val1, val2))
metadata = pd.DataFrame.from_dict(metadata, orient='index')
metadata.rename(columns = {metadata.columns[0]:'Condition'}, inplace=True)
metadata['Sample'] = metadata.index
metadata['Temp'] = metadata['Sample'].apply(lambda x:x.split(' ')[-1])
metadata.head()

         Condition    Sample Temp
Sample 1        OH  Sample 1    1
Sample 2        OH  Sample 2    2
Sample 3        OS  Sample 3    3
Sample 4        OS  Sample 4    4
Sample 5        OH  Sample 5    5

In [9]:
metadata[metadata['Sample'].isin(['Sample 3', 'Sample 16', 'Sample 17', 'Sample 24', 'Sample 27', 'Sample 28', 'Sample 31'])]

          Condition     Sample Temp
Sample 3         OS   Sample 3    3
Sample 16        OS  Sample 16   16
Sample 17        OH  Sample 17   17
Sample 24        OH  Sample 24   24
Sample 27        OH  Sample 27   27
Sample 28        OS  Sample 28   28
Sample 31        OS  Sample 31   31

# Extract metadata for EDA

In [9]:
meta.loc['!Sample_characteristics_ch1']

,Sample 1 [sss],Sample 2 [sss],Sample 3 [sss],Sample 4 [sss],Sample 5 [sss],Sample 6 [sss],Sample 7 [sss],Sample 8 [sss],Sample 9 [sss],Sample 10 [sss],...,Sample 31 [sss],Sample 32 [sss],Sample 33 [sss],Sample 34 [sss],Sample 35 [sss],Sample 36 [sss],Sample 37 [sss],Sample 38 [sss],Sample 39 [sss],Sample 40 [sss]
!Sample_title,,,,,,,,,,,,,,,,,,,,,
!Sample_characteristics_ch1,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,...,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent,population: Chinese descent
!Sample_characteristics_ch1,sarcopenia status: no,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: no,...,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes,sarcopenia status: no,sarcopenia status: yes,sarcopenia status: yes
!Sample_characteristics_ch1,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,...,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male,Sex: male
!Sample_characteristics_ch1,age (yr): 69,age (yr): 69,age (yr): 69,age (yr): 73,age (yr): 71,age (yr): 65,age (yr): 78,age (yr): 66,age (yr): 71,age (yr): 67,...,age (yr): 78,age (yr): 79,age (yr): 74,age (yr): 69,age (yr): 69,age (yr): 74,age (yr): 78,age (yr): 65,age (yr): 68,age (yr): 66
!Sample_characteristics_ch1,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,...,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle,tissue: vastus lateralis muscle

In [10]:
eda = {}
for i in range(0,5):
    key = meta.loc['!Sample_characteristics_ch1'].iloc[i][0].split(': ')[0]
    value = meta.loc['!Sample_characteristics_ch1'].iloc[i]
    value = value.apply(lambda x:x.split(': ')[-1])
    eda[key] = value

eda = pd.DataFrame(eda)

In [11]:
eda.head()

,population,sarcopenia status,Sex,age (yr),tissue
Sample 1 [sss],Chinese descent,no,male,69,vastus lateralis muscle
Sample 2 [sss],Chinese descent,no,male,69,vastus lateralis muscle
Sample 3 [sss],Chinese descent,yes,male,69,vastus lateralis muscle
Sample 4 [sss],Chinese descent,yes,male,73,vastus lateralis muscle
Sample 5 [sss],Chinese descent,no,male,71,vastus lateralis muscle

In [12]:
# eda.to_csv('./GSE111016_eda.csv')

# Preprocessing
다음은 유전자를 **Ensembl**에서 **GeneSymbol**로 바꿔주는 과정입니다.  
GSE111016에서 유전자는 **Ensembl**로 저장되어 있으며 GSE167186과 병합을 위해 다음 과정이 필요합니다.

## Ensembl to Symbol (by supplementary data 2)

In [13]:
supple = pd.read_csv('/Users/soheepark/03-GEO근감소/Data/GSE111016_SupplementaryDataset2.csv', index_col=0)
supple[:3]

,chr,gene_source,start,end,strand,gene_version,gene_name,gene_biotype,symbol.org.Hs.eg,title.org.Hs.eg,Amean,coef_sarc,modt_sarc,pval_sarc,adjp_sarc
ENSG00000214973,1,havana,27200834,27201473,-,3,CHCHD3P3,processed_pseudogene,NaN,NaN,2.246,-0.323,-5.154,0.000007,0.0796
ENSG00000130312,19,ensembl_havana,17292609,17306843,+,5,MRPL34,protein_coding,MRPL34,mitochondrial ribosomal protein L34,4.219,-0.373,-4.914,0.000015,0.0796
ENSG00000250479,22,ensembl_havana,23765834,23768443,-,7,CHCHD10,protein_coding,NaN,NaN,6.602,-0.337,-4.843,0.000018,0.0796

In [14]:
# counts 인덱스에 맞는 Supple Genesymbol을 매핑

counts['GeneSymbol'] = counts.index.map(supple['gene_name'])
print(f'Count of rows: {counts.shape[0]}')
counts.head()

Count of rows: 65217

,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,...,Sample 32,Sample 33,Sample 34,Sample 35,Sample 36,Sample 37,Sample 38,Sample 39,Sample 40,GeneSymbol
ENSG00000000003,124,145,61,110,122,120,145,118,108,125,...,119,79,67,134,114,106,128,149,122,TSPAN6
ENSG00000000005,7,6,10,16,124,9,37,3,6,45,...,3,6,35,5,16,8,6,27,18,TNMD
ENSG00000000419,536,839,415,690,825,852,774,838,629,708,...,739,639,462,780,551,576,788,742,656,DPM1
ENSG00000000457,402,538,244,486,538,549,629,525,430,453,...,405,431,292,494,443,395,551,483,438,SCYL3
ENSG00000000460,141,119,73,169,96,104,145,115,94,131,...,104,145,85,131,115,141,121,125,120,C1orf112

In [15]:
# Gene Symbol이 없는 EnsembleID는 삭제
print(f"Count of NA GeneSymbol {counts['GeneSymbol'].isna().sum()}")
counts.dropna(subset=['GeneSymbol'], inplace=True)
print(f'Count of rows: {counts.shape[0]}')

Count of NA GeneSymbol 48338
Count of rows: 16879

## Ensembl to Symbol (by supplementary dataset 2)

In [24]:
supple = pd.read_csv('/Users/soheepark/03-GEO근감소/Data/GSE111016_SupplementaryDataset2.csv', index_col=0)
supple.head()

,chr,gene_source,start,end,strand,gene_version,gene_name,gene_biotype,symbol.org.Hs.eg,title.org.Hs.eg,Amean,coef_sarc,modt_sarc,pval_sarc,adjp_sarc
ENSG00000214973,1,havana,27200834,27201473,-,3,CHCHD3P3,processed_pseudogene,NaN,NaN,2.246,-0.323,-5.154,0.000007,0.0796
ENSG00000130312,19,ensembl_havana,17292609,17306843,+,5,MRPL34,protein_coding,MRPL34,mitochondrial ribosomal protein L34,4.219,-0.373,-4.914,0.000015,0.0796
ENSG00000250479,22,ensembl_havana,23765834,23768443,-,7,CHCHD10,protein_coding,NaN,NaN,6.602,-0.337,-4.843,0.000018,0.0796
ENSG00000156411,14,ensembl_havana,103912288,103928269,-,8,C14orf2,protein_coding,C14orf2,chromosome 14 open reading frame 2,5.394,-0.302,-4.765,0.000024,0.0796
ENSG00000146147,6,ensembl_havana,53929982,54266280,+,13,MLIP,protein_coding,MLIP,muscular LMNA interacting protein,6.833,0.277,4.714,0.000028,0.0796

In [25]:
# counts 인덱스에 맞는 supple의 gene_name을 매핑

counts['GeneSymbol'] = counts.index.map(supple.gene_name)
print(f'Count of rows: {counts.shape[0]}')

Count of rows: 65217

In [32]:
# Gene Symbol이 na인 경우 삭제
print(f"NA counts of GeneSymbol: {counts['GeneSymbol'].isna().sum()}")
counts.dropna(subset=['GeneSymbol'], inplace=True)
print(f'Count of rows: {counts.shape[0]}')

NA counts of GeneSymbol: 48338
Count of rows: 16879

In [ ]:
# 'GeneSymbol' 컬럼을 인덱스로 설정하고 'EnsembleID' 컬럼 삭제

counts.set_index('GeneSymbol', inplace=True)
print(f'The shape of counts table: {counts.shape}')

In [ ]:
# 전체 샘플에서 발현량이 없는 유전자를 필터링합니다.
print(f'필터링 전 테이블: {counts.shape}')
counts = counts.loc[counts.sum(axis=1)>0]
print(f'필터링 후 테이블: {counts.shape}')

## Ensembl to Symbol (by pybiomart)
* https://pypi.org/project/pybiomart/

In [60]:
# # pip install pybiomart
# # http://www.ensembl.org/biomart
# from pybiomart import Server

# server = Server(host='http://www.ensembl.org')

# dataset = (server.marts['ENSEMBL_MART_ENSEMBL']
#                  .datasets['hsapiens_gene_ensembl'])

# dataset.query(attributes=['ensembl_gene_id', 'external_gene_name'],
#               filters={'chromosome_name': ['1','2']}).head()

    Gene stable ID    Gene name
0  ENSG00000290825      DDX11L2
1  ENSG00000223972      DDX11L1
2  ENSG00000227232       WASH7P
3  ENSG00000278267    MIR6859-1
4  ENSG00000243485  MIR1302-2HG

In [61]:
# from pybiomart import Dataset

# dataset = Dataset(name='hsapiens_gene_ensembl',
#                   host='http://www.ensembl.org')

# dataset.query(attributes=['ensembl_gene_id', 'external_gene_name'],
#               filters={'chromosome_name': ['1','2']}).head()

    Gene stable ID    Gene name
0  ENSG00000290825      DDX11L2
1  ENSG00000223972      DDX11L1
2  ENSG00000227232       WASH7P
3  ENSG00000278267    MIR6859-1
4  ENSG00000243485  MIR1302-2HG

## Ensembl to Symbol (by biomart)

In [12]:
# pip install biomart
# Original reference: https://github.com/sebriois/biomart
# Reference blog: https://autobencoder.com/2021-10-03-gene-conversion/
# Reference 2: https://bioconductor.riken.jp/packages/3.4/bioc/vignettes/biomaRt/inst/doc/biomaRt.html

import biomart

def get_ensembl_mappings():                                   
    # 서버 연결 세팅
    server = biomart.BiomartServer('http://www.ensembl.org/biomart')         
    mart = server.datasets['hsapiens_gene_ensembl']                            

    # 원하는 타입의 어노테이션을 작성
    attributes = ['ensembl_gene_id', 'hgnc_symbol'] # ensembl_transcript_id

    # 매핑
    response = mart.search({'attributes': attributes})                          
    data = response.raw.data.decode('ascii')                                    

    # 딕셔너리에 저장
    ensembl_to_genesymbol = {}                                                  
    for line in data.splitlines():                                              
        line = line.split('\t')                                                 

        ensembl_gene = line[0]
        gene_symbol = line[1]

        ensembl_to_genesymbol[ensembl_gene] = ensembl_gene
        ensembl_to_genesymbol[ensembl_gene] = gene_symbol

        
    return ensembl_to_genesymbol

In [13]:
# ensemble genesymbol 매핑 데이터프레임 생성

map_dict = get_ensembl_mappings()
map_dict

{'ENSG00000210049': 'MT-TF',
 'ENSG00000211459': 'MT-RNR1',
 'ENSG00000210077': 'MT-TV',
 'ENSG00000210082': 'MT-RNR2',
 'ENSG00000209082': 'MT-TL1',
 'ENSG00000198888': 'MT-ND1',
 'ENSG00000210100': 'MT-TI',
 'ENSG00000210107': 'MT-TQ',
 'ENSG00000210112': 'MT-TM',
 'ENSG00000198763': 'MT-ND2',
 'ENSG00000210117': 'MT-TW',
 'ENSG00000210127': 'MT-TA',
 'ENSG00000210135': 'MT-TN',
 'ENSG00000210140': 'MT-TC',
 'ENSG00000210144': 'MT-TY',
 'ENSG00000198804': 'MT-CO1',
 'ENSG00000210151': 'MT-TS1',
 'ENSG00000210154': 'MT-TD',
 'ENSG00000198712': 'MT-CO2',
 'ENSG00000210156': 'MT-TK',
 'ENSG00000228253': 'MT-ATP8',
 'ENSG00000198899': 'MT-ATP6',
 'ENSG00000198938': 'MT-CO3',
 'ENSG00000210164': 'MT-TG',
 'ENSG00000198840': 'MT-ND3',
 'ENSG00000210174': 'MT-TR',
 'ENSG00000212907': 'MT-ND4L',
 'ENSG00000198886': 'MT-ND4',
 'ENSG00000210176': 'MT-TH',
 'ENSG00000210184': 'MT-TS2',
 'ENSG00000210191': 'MT-TL2',
 'ENSG00000198786': 'MT-ND5',
 'ENSG00000198695': 'MT-ND6',
 'ENSG00000210194': 'MT-TE',
 'ENSG00000198727': 'MT-CYB',
 'ENSG00000210195': 'MT-TT',
 'ENSG00000210196': 'MT-TP',
 'ENSG00000271254': '',
 'ENSG00000278625': '',
 'ENSG00000278457': '',
 'ENSG00000276197': '',
 'ENSG00000277428': '',
 'ENSG00000278573': '',
 'ENSG00000278704': '',
 'ENSG00000273748': '',
 'ENSG00000275661': '',
 'ENSG00000274202': '',
 'ENSG00000277630': '',
 'ENSG00000277400': '',
 'ENSG00000274917': 'RNA5-8SN5',
 'ENSG00000278294': '',
 'ENSG00000276256': '',
 'ENSG00000277196': '',
 'ENSG00000276351': '',
 'ENSG00000274847': 'MAFIP',
 'ENSG00000273730': '',
 'ENSG00000273937': '',
 'ENSG00000276345': '',
 'ENSG00000273532': '',
 'ENSG00000278793': '',
 'ENSG00000276932': '',
 'ENSG00000278817': '',
 'ENSG00000276711': '',
 'ENSG00000276017': '',
 'ENSG00000278633': '',
 'ENSG00000278066': '',
 'ENSG00000276312': '',
 'ENSG00000276700': 'RNA5-8SN4',
 'ENSG00000275757': '',
 'ENSG00000273739': '',
 'ENSG00000275063': '',
 'ENSG00000277856': '',
 'ENSG00000277374': '',
 'ENSG00000291360': 'RPL23AP45',
 'ENSG00000278384': '',
 'ENSG00000278673': '',
 'ENSG00000275987': '',
 'ENSG00000277890': '',
 'ENSG00000268674': '',
 'ENSG00000275249': '',
 'ENSG00000277475': '',
 'ENSG00000275405': '',
 'ENSG00000274792': '',
 'ENSG00000276872': '',
 'ENSG00000276760': '',
 'ENSG00000277927': '',
 'ENSG00000291371': '',
 'ENSG00000291372': 'RNU6-409P',
 'ENSG00000291368': 'ACR',
 'ENSG00000291369': '',
 'ENSG00000291370': '',
 'ENSG00000292254': '',
 'ENSG00000274175': '',
 'ENSG00000273554': '',
 'ENSG00000275869': '',
 'ENSG00000278510': '',
 'ENSG00000273843': '',
 'ENSG00000277836': '',
 'ENSG00000291410': '',
 'ENSG00000291411': '',
 'ENSG00000291412': '',
 'ENSG00000291413': '',
 'ENSG00000291414': 'MIR4740',
 'ENSG00000291415': 'MIR3186',
 'ENSG00000291416': '',
 'ENSG00000291417': 'LINC01971',
 'ENSG00000291418': '',
 'ENSG00000291420': 'ACTG1',
 'ENSG00000288522': '',
 'ENSG00000288204': 'HMX1',
 'ENSG00000288247': '',
 'ENSG00000291421': 'BAHCC1',
 'ENSG00000291422': '',
 'ENSG00000291423': '',
 'ENSG00000291424': '',
 'ENSG00000291425': 'LINC03048',
 'ENSG00000288372': '',
 'ENSG00000288288': '',
 'ENSG00000288129': '',
 'ENSG00000288472': 'LINC03015',
 'ENSG00000288417': 'LINC03014',
 'ENSG00000288502': '',
 'ENSG00000288311': '',
 'ENSG00000288449': '',
 'ENSG00000288499': 'FAM20C',
 'ENSG00000288159': '',
 'ENSG00000288431': '',
 'ENSG00000281819': 'NAA50P1',
 'ENSG00000263150': 'OR8J2',
 'ENSG00000262851': 'OR5T2',
 'ENSG00000261897': 'OR5T3',
 'ENSG00000262784': 'OR5T1',
 'ENSG00000262611': 'OR8H1',
 'ENSG00000280712': 'OR8I1P',
 'ENSG00000262755': 'OR8K3',
 'ENSG00000281773': 'FAM8A2P',
 'ENSG00000280617': 'OR8K2P',
 'ENSG00000263328': 'OR8K1',
 'ENSG00000281820': 'RPL5P29',
 'ENSG00000262796': 'OR8J1',
 'ENSG00000262315': 'OR8U8',
 'ENSG00000281038': 'OR8U9',
 'ENSG00000280577': 'OR8L1P',
 'ENSG00000288269': 'GCGR',
 'ENSG00000288213': 'MCRIP1',
 'ENSG00000288319': '',
 'ENSG00000288521': '',
 'ENSG00000288394': 'ABCD1P4',
 'ENSG00000288228': '',
 'ENSG00000288342': 'PABPC1P9',
 'ENSG00000288315': 'SLC9B1P4',
 'ENSG00000288272': 'ACTR3BP6',
 'ENSG00000288186': 'PPP1R27',
 'ENSG00000282162': 'LINC01784',
 'ENSG00000281934': 'PRAMEF11',
 'ENSG00000282116': 'PRAMEF30P',
 'ENSG00000282175': 'HNRNPCL1',
 'ENSG00000282817': 'PRAMEF2',
 'ENSG00000282584': 'PRAMEF4',
 'ENSG00000282663': 'PRAMEF10',
 'ENSG00000279195': 'PRAMEF7',
 'ENSG00000282338': 'RNU6-1072P',
 'ENSG00000282549': 'PRAMEF29P',
 'ENSG00000282119': 'PRAMEF6',
 'ENSG00000282791': 'PRAMEF28P',
 'ENSG00000282437': 'PRAMEF27',
 'ENSG00000282559': 'HNRNPCL3',
 'ENSG00000282566': 'PRAMEF25',
 'ENSG00000282258': 'PRAMEF34P',
 'ENSG00000282562': 'PRAMEF35P',
 'ENSG00000282530': 'HNRNPCL2',
 'ENSG00000282468': 'PRAMEF36P',
 'ENSG00000290624': '',
 'ENSG00000282341': '',
 'ENSG00000281987': 'PRAMEF26',
 'ENSG00000290500': '',
 'ENSG00000282095': 'HNRNPCL4',
 'ENSG00000261958': 'OR9G1',
 'ENSG00000282298': 'PRAMEF9',
 'ENSG00000262191': 'OR9G9',
 'ENSG00000281683': '',
 'ENSG00000282741': 'PRAMEF13',
 'ENSG00000262268': 'OR9G3P',
 'ENSG00000262647': 'OR9G4',
 'ENSG00000282212': 'PRAMEF18',
 'ENSG00000281777': 'OR9G2P',
 'ENSG00000282289': 'PRAMEF31P',
 'ENSG00000282424': 'PRAMEF5',
 'ENSG00000281313': 'OR5G1P',
 'ENSG00000281279': 'OR5G4P',
 'ENSG00000282216': 'PRAMEF32P',
 'ENSG00000282288': 'RNU6-771P',
 'ENSG00000262535': 'OR5G5P',
 'ENSG00000282583': 'PRAMEF8',
 'ENSG00000281107': 'OR5G3',
 'ENSG00000281839': 'LINC02735',
 'ENSG00000282125': 'PRAMEF33',
 'ENSG00000293551': 'PRAMEF22',
 'ENSG00000291378': 'ARHGEF19-AS1',
 'ENSG00000291381': 'ARHGEF19',
 'ENSG00000291405': '',
 'ENSG00000288263': 'GRK1',
 'ENSG00000291404': 'ANO7L1',
 'ENSG00000291376': '',
 'ENSG00000291382': 'CPLANE2',
 'ENSG00000288305': 'LINC00552',
 'ENSG00000291377': 'MT1XP1',
 'ENSG00000291375': 'FBXO42',
 'ENSG00000291379': 'SZRD1',
 'ENSG00000291374': 'RPL22P3',
 'ENSG00000291401': 'SPATA21',
 'ENSG00000291380': 'NECAP2',
 'ENSG00000291388': 'LINC01772',
 'ENSG00000291402': 'CROCCP3',
 'ENSG00000291389': 'RNU1-1',
 'ENSG00000291390': '',
 'ENSG00000291391': '',
 'ENSG00000291392': 'LINC01783',
 'ENSG00000291393': 'RNU1-6P',
 'ENSG00000291394': 'PDE4DIPP8',
 'ENSG00000291386': '',
 'ENSG00000291385': 'RNU1-2',
 'ENSG00000291408': '',
 'ENSG00000291384': '',
 'ENSG00000291400': '',
 'ENSG00000291383': 'RNU1-5P',
 'ENSG00000291395': '',
 'ENSG00000291397': '',
 'ENSG00000291398': 'EIF1AXP1',
 'ENSG00000291396': 'RNU1-3',
 'ENSG00000291399': 'RNU1-4',
 'ENSG00000291387': 'PADI2',
 'ENSG00000292230': '',
 'ENSG00000291403': 'CROCCP4',
 'ENSG00000292231': '',
 'ENSG00000291407': '',
 'ENSG00000292235': '',
 'ENSG00000292236': '',
 'ENSG00000292238': '',
 'ENSG00000292239': '',
 'ENSG00000292240': '',
 'ENSG00000292241': '',
 'ENSG00000292242': '',
 'ENSG00000292229': '',
 'ENSG00000291426': 'TOLLIP',
 'ENSG00000292226': '',
 'ENSG00000292228': '',
 'ENSG00000291427': 'TOLLIP-DT',
 'ENSG00000291429': '',
 'ENSG00000291430': 'LINC02689',
 'ENSG00000291428': 'BRSK2',
 'ENSG00000292227': '',
 'ENSG00000292225': 'NBPF1',
 'ENSG00000291441': '',
 'ENSG00000291431': 'DUSP8',
 'ENSG00000291432': 'KRTAP5-AS1',
 'ENSG00000291433': 'KRTAP5-1',
 'ENSG00000291434': 'KRTAP5-2',
 'ENSG00000291435': 'KRTAP5-3',
 'ENSG00000291440': 'KRTAP5-4',
 'ENSG00000291443': 'KRTAP5-5',
 'ENSG00000291436': '',
 'ENSG00000291437': 'FAM99A',
 'ENSG00000291438': 'FAM99B',
 'ENSG00000291439': 'LINC02708',
 'ENSG00000291442': 'MOB2',
 'ENSG00000291444': 'RBMY3AP',
 'ENSG00000291445': 'CDY3P',
 'ENSG00000291446': 'TSPY25P',
 'ENSG00000291447': 'USP9YP22',
 'ENSG00000291448': 'TSPY16P',
 'ENSG00000291449': 'USP9YP4',
 'ENSG00000291450': 'ELOCP4',
 'ENSG00000291451': 'RBMY1A3P',
 'ENSG00000291452': '',
 'ENSG00000291453': 'TTTY20',
 'ENSG00000291455': 'TSPY8',
 'ENSG00000291456': 'FAM197Y7',
 'ENSG00000291457': '',
 'ENSG00000291458': 'TSPY4',
 'ENSG00000291459': 'TSPY9',
 'ENSG00000291460': 'FAM197Y2',
 'ENSG00000291461': 'FAM197Y4',
 'ENSG00000291462': 'FAM197Y4',
 'ENSG00000291454': 'FAM197Y8',
 'ENSG00000293355': 'FAM197Y8',
 'ENSG00000281449': 'BCL2L14',
 'ENSG00000285019': 'ELOCP5',
 'ENSG00000285196': 'CDY10P',
 'ENSG00000285308': 'USP9YP3',
 'ENSG00000281442': 'PTMAP9',
 'ENSG00000283344': 'MIR1244-4',
 'ENSG00000281324': 'LRP6',
 'ENSG00000285028': 'USP9YP8',
 'ENSG00000285455': 'CDY11P',
 'ENSG00000285477': 'OFD1P16Y',
 'ENSG00000280475': 'RPL21P100',
 'ENSG00000206783': 'RNU6-545P',
 'ENSG00000281874': '',
 'ENSG00000207477': 'RNU6-318P',
 'ENSG00000281818': 'MANSC1',
 'ENSG00000281051': 'RPL23AP66',
 'ENSG00000281234': 'LOH12CR2',
 'ENSG00000280689': 'BORCS5',
 'ENSG00000281168': '',
 'ENSG00000280962': 'DUSP16',
 'ENSG00000281671': '',
 'ENSG00000281525': '',
 'ENSG00000282467': '',
 'ENSG00000292327': 'PPP2R3B',
 'ENSG00000292328': 'RPL14P5',
 'ENSG00000292329': '',
 'ENSG00000292330': '',
 'ENSG00000292331': 'ASMTL-AS1',
 'ENSG00000292332': 'IL3RA',
 'ENSG00000292333': 'P2RY8',
 'ENSG00000292334': 'SLC25A6',
 'ENSG00000292335': '',
 'ENSG00000292336': 'ASMT',
 'ENSG00000292337': 'DHRSX-IT1',
 'ENSG00000288406': '',
 'ENSG00000292338': 'DHRSX',
 'ENSG00000292339': 'ASMTL',
 'ENSG00000292340': 'LINC02968',
 'ENSG00000292341': 'LINC00106',
 'ENSG00000292342': 'LINC00685',
 'ENSG00000292343': 'AKAP17A',
 'ENSG00000292344': 'PLCXD1',
 'ENSG00000292345': 'ZBED1',
 'ENSG00000292346': 'MIR6089',
 'ENSG00000292347': 'LINC00102',
 'ENSG00000292348': 'CD99',
 'ENSG00000292349': '',
 'ENSG00000292350': '',
 'ENSG00000292351': '',
 'ENSG00000292352': 'FABP5P13',
 'ENSG00000292353': 'KRT18P53',
 'ENSG00000292354': 'SHOX',
 'ENSG00000292355': 'MIR3690',
 'ENSG00000292356': 'RNA5SP498',
 'ENSG00000292357': 'CSF2RA',
 'ENSG00000292358': 'GTPBP6',
 'ENSG00000292359': '',
 'ENSG00000292360': 'LINC03112',
 'ENSG00000292361': 'CD99P1',
 'ENSG00000292362': 'CD99P1',
 'ENSG00000292363': 'CRLF2',
 'ENSG00000292364': 'AMD1P2',
 'ENSG00000292365': 'DPH3P2',
 'ENSG00000292366': 'VAMP7',
 'ENSG00000292367': 'ELOCP24',
 'ENSG00000292368': 'TRPC6P1',
 'ENSG00000292369': '',
 'ENSG00000292370': 'WASIR1',
 'ENSG00000292371': 'DDX11L16',
 'ENSG00000292372': 'WASH6P',
 'ENSG00000292373': 'IL9R',
 'ENSG00000215601': 'TSPY24P',
 'ENSG00000215603': 'ZNF92P1Y',
 'ENSG00000225878': 'SERBP1P2',
 'ENSG00000236435': 'TSPY12P',
 'ENSG00000258991': 'DUX4L19',
 'ENSG00000237048': 'TTTY12',
 'ENSG00000224518': '',
 'ENSG00000231988': 'OFD1P3Y',
 'ENSG00000238073': 'RBMY2HP',
 'ENSG00000275866': '',
 'ENSG00000131538': 'TTTY6',
 'ENSG00000271595': 'ELOCP35',
 'ENSG00000183704': 'SLC9B1P1',
 'ENSG00000232927': 'USP12PY',
 'ENSG00000277438': 'KDM5DP1',
 'ENSG00000286217': 'LINC00279',
 'ENSG00000259154': 'DUX4L17',
 'ENSG00000169789': 'PRY',
 'ENSG00000273589': '',
 'ENSG00000273863': '',
 'ENSG00000228571': 'HSFY7P',
 'ENSG00000288260': '',
 'ENSG00000271375': '',
 'ENSG00000224634': 'ZNF736P6Y',
 'ENSG00000285470': 'TUSC2P1',
 'ENSG00000288430': 'RNU5B-4P',
 'ENSG00000226092': 'RBMY2AP',
 'ENSG00000288297': 'ECSCR',
 'ENSG00000234620': 'PUDPP1',
 'ENSG00000236690': '',
 'ENSG00000273693': 'CDRT15P10',
 'ENSG00000114374': 'USP9Y',
 'ENSG00000288274': 'SMIM33',
 'ENSG00000288243': 'STING1',
 'ENSG00000288388': '',
 'ENSG00000288138': 'NCOA4P4',
 'ENSG00000169807': 'PRY2',
 'ENSG00000223422': '',
 'ENSG00000231159': 'OFD1P8Y',
 'ENSG00000225653': 'RNF19BPY',
 'ENSG00000251618': '',
 'ENSG00000229159': 'TSPY23P',
 'ENSG00000228578': 'TUBB1P2',
 'ENSG00000275280': '',
 'ENSG00000270242': 'ACTR3BP1',
 'ENSG00000236477': 'RPS24P1',
 'ENSG00000237997': 'RCC2P2',
 'ENSG00000244246': 'ZNF736P8Y',
 'ENSG00000198692': 'EIF1AY',
 'ENSG00000183753': 'BPY2',
 'ENSG00000225433': 'MTND1P12',
 'ENSG00000227166': 'STSP1',
 'ENSG00000235857': 'CTBP2P1',
 'ENSG00000223955': 'MTND6P1',
 'ENSG00000270455': 'PABPC1P5',
 'ENSG00000229940': 'TSPY22P',
 'ENSG00000234385': 'RCC2P1',
 'ENSG00000226863': 'SHROOM2P1',
 'ENSG00000237968': '',
 'ENSG00000233699': 'TTTY18',
 'ENSG00000286009': '',
 'ENSG00000271365': '',
 'ENSG00000259029': 'DUX4L18',
 'ENSG00000286201': '',
 'ENSG00000215537': 'ZNF736P11Y',
 'ENSG00000230476': 'OFD1P9Y',
 'ENSG00000229745': 'BPY2DP',
 'ENSG00000227204': 'RBMY2JP',
 'ENSG00000275828': 'CHEK2P1',
 'ENSG00000225615': 'RBMY2UP',
 'ENSG00000230663': 'FAM224B',
 'ENSG00000232522': 'ZNF886P',
 'ENSG00000234131': 'ELOCP8',
 'ENSG00000277519': 'OFD1P16Y',
 'ENSG00000259247': 'TTTY25P',
 'ENSG00000273731': '',
 'ENSG00000236951': '',
 'ENSG00000215583': 'ASS1P6',
 'ENSG00000274162': 'SNX18P1Y',
 'ENSG00000227444': '',
 'ENSG00000233774': 'MED14P1',
 'ENSG00000232475': 'HSFY5P',
 'ENSG00000228764': 'ZNF885P',
 'ENSG00000232226': 'ARSFP1',
 'ENSG00000224567': '',
 'ENSG00000241200': 'ZNF736P7Y',
 'ENSG00000228518': 'SURF6P1',
 'ENSG00000227447': 'XGY1',
 'ENSG00000274231': '',
 'ENSG00000286050': '',
 'ENSG00000274502': 'ANKRD20A6P',
 'ENSG00000278854': '',
 'ENSG00000225809': 'RBMY2KP',
 'ENSG00000237902': 'TSPY21P',
 'ENSG00000232419': 'TTTY19',
 'ENSG00000226906': 'TTTY4',
 'ENSG00000230025': '',
 'ENSG00000235649': 'MXRA5Y',
 'ENSG00000258567': 'DUX4L16',
 'ENSG00000234179': 'MTCYBP1',
 'ENSG00000271309': '',
 'ENSG00000229553': 'USP9YP17',
 'ENSG00000228240': 'TTTY17A',
 'ENSG00000234652': 'AGPAT5P1',
 'ENSG00000218410': '',
 'ENSG00000224989': 'FAM41AY1',
 'ENSG00000131548': 'TTTY6B',
 'ENSG00000232029': 'ELOCP15',
 'ENSG00000273858': '',
 'ENSG00000227830': 'TRIM60P3Y',
 'ENSG00000226529': 'MTND1P1',
 'ENSG00000274837': '',
 'ENSG00000216777': 'PRRC2CP1',
 'ENSG00000216824': 'ZNF736P10Y',
 'ENSG00000276829': '',
 'ENSG00000228850': 'CDY12P',
 'ENSG00000283076': '',
 'ENSG00000234850': 'MTND2P3',
 'ENSG00000224873': 'CDY13P',
 'ENSG00000229234': 'RBMY1KP',
 'ENSG00000270570': '',
 'ENSG00000223517': '',
 'ENSG00000228207': '',
 'ENSG00000224917': '',
 'ENSG00000286187': '',
 'ENSG00000225117': 'ARSDP1',
 'ENSG00000215560': 'TTTY5',
 'ENSG00000228411': 'CDY4P',
 'ENSG00000235059': '',
 'ENSG00000244395': 'RBMY1D',
 'ENSG00000230727': 'RBMY2WP',
 'ENSG00000230814': 'USP9YP24',
 'ENSG00000229725': '',
 'ENSG00000229236': 'TTTY10',
 'ENSG00000229518': 'UBE2V1P3',
 'ENSG00000232730': 'FAM8A4P',
 'ENSG00000229308': '',
 'ENSG00000244000': '',
 'ENSG00000232764': 'TRIM60P8Y',
 'ENSG00000236131': 'MED13P1',
 'ENSG00000227949': 'CYCSP46',
 'ENSG00000252900': 'RNU6-303P',
 'ENSG00000252689': '',
 'ENSG00000243980': 'RN7SL702P',
 'ENSG00000252315': 'RNA5SP520',
 'ENSG00000252012': 'RNA5SP521',
 'ENSG00000273966': '',
 'ENSG00000252173': 'RNU6-109P',
 'ENSG00000252323': 'RNU6-184P',
 'ENSG00000169953': 'HSFY2',
 'ENSG00000236429': 'GPM6BP2',
 'ENSG00000249501': 'USP9YP2',
 'ENSG00000228193': 'ELOCP14',
 'ENSG00000248573': 'PRYP6',
 'ENSG00000230904': 'XKRYP2',
 'ENSG00000238135': 'USP9YP10',
 'ENSG00000224151': 'USP9YP28',
 'ENSG00000251970': 'RNU1-41P',
 'ENSG00000238088': 'OFD1P7Y',
 'ENSG00000217179': 'MTCYBP2',
 'ENSG00000217896': 'ZNF839P1',
 'ENSG00000185275': 'CD24P4',
 'ENSG00000252766': 'RNU6-255P',
 'ENSG00000274282': '',
 'ENSG00000234529': 'GAPDHP19',
 'ENSG00000238191': 'CLUHP1',
 'ENSG00000226353': 'TAF9P1',
 'ENSG00000275578': '',
 'ENSG00000226449': 'CDY5P',
 'ENSG00000225896': 'ELOCP36',
 'ENSG00000224166': 'PRYP1',
 'ENSG00000229129': 'ACTG1P2',
 'ENSG00000223555': 'USP9YP23',
 'ENSG00000235521': 'USP9YP27',
 'ENSG00000252513': 'RNU1-128P',
 'ENSG00000224964': 'TRAPPC2P3',
 'ENSG00000226011': 'OFD1P1Y',
 'ENSG00000225740': 'ELOCP6',
 'ENSG00000229138': 'CDY6P',
 'ENSG00000224485': 'USP9YP7',
 'ENSG00000226116': 'USP9YP6',
 'ENSG00000237558': 'CDY7P',
 'ENSG00000233378': 'USP9YP34',
 'ENSG00000237616': 'USP9YP32',
 'ENSG00000224033': 'CDY8P',
 'ENSG00000230412': 'ELOCP12',
 'ENSG00000225895': 'TRAPPC2P8',
 'ENSG00000233120': 'USP9YP15',
 'ENSG00000252166': 'RNU1-95P',
 'ENSG00000232744': 'USP9YP16',
 'ENSG00000229465': 'ACTG1P11',
 'ENSG00000231311': 'PRYP2',
 'ENSG00000236599': 'ELOCP26',
 'ENSG00000232899': 'CDY9P',
 'ENSG00000229302': 'TAF9P2',
 'ENSG00000228945': 'CLUHP2',
 'ENSG00000233522': 'FAM224A',
 'ENSG00000278391': '',
 'ENSG00000251953': 'RNA5SP522',
 'ENSG00000252667': 'RNA5SP523',
 'ENSG00000249726': 'TUBB1P1',
 'ENSG00000225716': 'ELOCP13',
 'ENSG00000229406': 'OFD1P4Y',
 'ENSG00000227494': 'USP9YP14',
 'ENSG00000252209': 'RNU1-48P',
 'ENSG00000249634': 'USP9YP5',
 'ENSG00000251510': '',
 'ENSG00000238067': 'XKRYP1',
 'ENSG00000233546': 'PRYP5',
 'ENSG00000230377': 'ELOCP7',
 'ENSG00000250951': 'USP9YP1',
 'ENSG00000230458': 'GPM6BP1',
 'ENSG00000131007': 'TTTY9B',
 'ENSG00000235479': 'RAB9AP4',
 'ENSG00000249606': 'TRAPPC2P7',
 'ENSG00000176728': 'TTTY14',
 'ENSG00000267793': '',
 'ENSG00000260197': '',
 'ENSG00000288049': '',
 'ENSG00000012817': 'KDM5D',
 'ENSG00000172468': 'HSFY1',
 'ENSG00000176679': 'TGIF2LY',
 'ENSG00000169800': 'RBMY1F',
 'ENSG00000182415': 'CDY2A',
 'ENSG00000233126': 'ZNF736P3Y',
 'ENSG00000227251': 'TRIM60P9Y',
 'ENSG00000252633': 'RN7SKP282',
 'ENSG00000251996': '',
 'ENSG00000252155': 'RNU6-941P',
 'ENSG00000252472': 'RNU6-521P',
 'ENSG00000224953': 'SRIP3',
 'ENSG00000274365': '',
 'ENSG00000233634': 'GOT2P5',
 'ENSG00000237701': 'ATP5PFP1',
 'ENSG00000273906': '',
 'ENSG00000232976': 'TRIM60P10Y',
 'ENSG00000226270': 'ZNF736P2Y',
 'ENSG00000227837': 'TRIM60P11Y',
 'ENSG00000278602': '',
 'ENSG00000223978': 'ZNF736P1Y',
 'ENSG00000278197': '',
 'ENSG00000230819': 'ZNF736P5Y',
 'ENSG00000185894': 'BPY2C',
 'ENSG00000228296': 'TTTY4C',
 'ENSG00000205916': 'DAZ4',
 'ENSG00000129873': 'CDY2B',
 'ENSG00000251841': 'RNU6-1334P',
 'ENSG00000184895': 'SRY',
 'ENSG00000237659': 'RNASEH2CP1',
 'ENSG00000232195': 'TOMM22P2',
 'ENSG00000286130': '',
 'ENSG00000129824': 'RPS4Y1',
 'ENSG00000229163': 'NAP1L1P2',
 'ENSG00000278847': '',
 'ENSG00000067646': 'ZFY',
 'ENSG00000233070': 'ZFY-AS1',
 'ENSG00000223600': 'EEF1A1P41',
 'ENSG00000215414': 'PSMA6P1',
 'ENSG00000224035': 'SFPQP1',
 'ENSG00000223915': 'DPPA2P1',
 'ENSG00000067048': 'DDX3Y',
 'ENSG00000288512': 'C1R',
 'ENSG00000234059': 'CASKP1',
 'ENSG00000183878': 'UTY',
 'ENSG00000288124': 'C1RL',
 'ENSG00000288352': 'C1RL-AS1',
 'ENSG00000288369': 'RBP5',
 'ENSG00000284403': 'RNU6-485P',
 'ENSG00000288383': '',
 'ENSG00000288427': 'CLSTN3',
 'ENSG00000288281': '',
 'ENSG00000288116': '',
 'ENSG00000288217': 'PEX5',
 'ENSG00000154620': 'TMSB4Y',
 'ENSG00000129864': 'VCY',
 'ENSG00000187191': 'DAZ3',
 'ENSG00000188120': 'DAZ1',
 'ENSG00000205936': 'PPP1R12BP2',
 'ENSG00000251925': '',
 'ENSG00000286744': '',
 'ENSG00000225189': 'REREP1Y',
 'ENSG00000230073': '',
 'ENSG00000236647': '',
 'ENSG00000099721': 'AMELY',
 'ENSG00000092377': 'TBL1Y',
 'ENSG00000288463': '',
 'ENSG00000232583': 'GPR143YP',
 'ENSG00000205944': 'DAZ2',
 'ENSG00000226555': 'AGKP1',
 'ENSG00000228787': 'NLGN4Y-AS1',
 'ENSG00000242389': 'RBMY1E',
 'ENSG00000165246': 'NLGN4Y',
 'ENSG00000288135': '',
 'ENSG00000288322': '',
 'ENSG00000288356': '',
 'ENSG00000288117': '',
 'ENSG00000231535': 'LINC00278',
 'ENSG00000229343': 'CDY22P',
 'ENSG00000232695': 'ELOCP17',
 'ENSG00000235511': 'OFD1P18Y',
 'ENSG00000232914': 'TRAPPC2P4',
 'ENSG00000223655': 'RAB9AP3',
 'ENSG00000230854': 'USP9YP20',
 'ENSG00000252625': 'RNU1-40P',
 'ENSG00000227635': 'USP9YP21',
 'ENSG00000237546': 'XKRYP6',
 'ENSG00000172283': 'PRYP4',
 'ENSG00000227867': 'ELOCP11',
 'ENSG00000231716': 'CDY23P',
 'ENSG00000234744': 'USP9YP26',
 'ENSG00000233156': 'HSFY8P',
 'ENSG00000234888': 'OFD1P15Y',
 'ENSG00000235014': 'REREP2Y',
 'ENSG00000289705': '',
 'ENSG00000225876': '',
 'ENSG00000251796': '',
 'ENSG00000229238': 'PPP1R12BP1',
 'ENSG00000252948': 'RNU6-1314P',
 'ENSG00000233843': 'CYCSP48',
 'ENSG00000188399': 'ANKRD36P1',
 'ENSG00000277146': '',
 'ENSG00000129862': 'VCY1B',
 'ENSG00000235451': 'PNPLA4P1',
 'ENSG00000289706': '',
 'ENSG00000226611': 'OFD1P2Y',
 'ENSG00000240438': 'OFD1P5Y',
 'ENSG00000286247': '',
 'ENSG00000225624': 'TBL1YP1',
 'ENSG00000280969': 'RPS4Y2',
 'ENSG00000224482': 'HSFY4P',
 'ENSG00000216844': '',
 'ENSG00000229551': 'GAPDHP17',
 'ENSG00000226504': 'TMEM167AP1',
 'ENSG00000254488': '',
 'ENSG00000237427': 'TOMM22P1',

In [14]:
# counts 인덱스에 맞는 map_dict의 Genesymbol을 매핑

counts['GeneSymbol'] = counts.index.map(map_dict)
print(f'Count of rows: {counts.shape[0]}')

Count of rows: 65217

In [15]:
# Gene Symbol이 없는 EnsembleID는 삭제

counts.dropna(subset=['GeneSymbol'], inplace=True)
print(f'Count of rows: {counts.shape[0]}')

Count of rows: 60466

In [16]:
# Gene Symbol열에 공백인 행 발견함
counts = counts[counts['GeneSymbol']!='']
print(f'Count of rows: {counts.shape[0]}')

Count of rows: 43369

In [17]:
# 'GeneSymbol' 컬럼을 인덱스로 설정하고 'EnsembleID' 컬럼 삭제

counts.set_index('GeneSymbol', inplace=True)
print(f'The shape of counts table: {counts.shape}')

The shape of counts table: (43369, 40)

## 이슈 (해결)
매핑하면서 Ensembl ID에서 공동으로 매핑되는 GeneSymbol이 존재함.  
-> Sum 값 활용

In [18]:
my_list = counts.columns.tolist()

common_items = set()

for item in my_list:
    if my_list.count(item) > 1:  # 리스트에서 해당 아이템이 두 번 이상 나타나면
        common_items.add(item)   # 공통 아이템 세트에 추가

In [19]:
counts[common_items]

Empty DataFrame
Columns: []
Index: [TSPAN6, TNMD, DPM1, SCYL3, FIRRM, FGR, CFH, FUCA2, GCLC, NFYA, STPG1, NIPAL3, LAS1L, ENPP4, SEMA3F, CFTR, ANKIB1, CYP51A1, KRIT1, RAD52, MYH16, BAD, LAP3, CD99, HS3ST1, AOC1, WNT16, HECW1, MAD1L1, LASP1, SNX11, TMEM176A, M6PR, KLHL13, CYP26B1, ICA1, DBNDD1, ALS2, CASP10, CFLAR, TFPI, NDUFAF7, RBM5, MTMR7, SLC7A2, ARF5, SARM1, POLDIP2, PLXND1, AK2, CD38, FKBP4, KDM1A, RBM6, CAMKK1, RECQL, VPS50, HSPB6, ARHGAP33, NDUFAB1, PDK4, SLC22A16, ZMYND10, ABCB5, ARX, SLC25A13, ST7, CDC27, SLC4A1, CALCR, HCCS, DVL2, PRSS22, UPF1, SKAP2, SLC25A5, MCUB, HOXA11, POLR2J, DHX33, MEOX1, THSD7A, LIG3, RPAP3, ACSM3, REXO5, CIAPIN1, SPPL2B, ATOSB, COPZ2, PRKAR2B, MSL3, CREBBP, TSPOAP1, MPO, PON1, GCFC2, WDR54, CROT, ABCB4, ...]

[43369 rows x 0 columns]

In [20]:
print(f'원 데이터: {counts.shape}')
counts = counts.groupby(counts.index).sum()
print(f'공동 유전자 sum: {counts.shape}')
counts.head()

원 데이터: (43369, 40)
공동 유전자 sum: (40063, 40)

,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,...,Sample 31,Sample 32,Sample 33,Sample 34,Sample 35,Sample 36,Sample 37,Sample 38,Sample 39,Sample 40
GeneSymbol,,,,,,,,,,,,,,,,,,,,,
A1BG,0,7,0,1,5,3,3,3,0,4,...,7,5,1,1,4,2,2,3,2,2
A1BG-AS1,14,13,3,17,18,21,7,12,12,26,...,16,13,10,2,13,16,12,17,24,9
A1CF,1,1,2,4,0,0,3,2,0,1,...,0,0,0,0,1,3,1,1,2,1
A2M,7145,9004,3427,6806,6684,8837,7772,7157,5560,6838,...,6439,7099,5109,3326,5538,8194,6718,8848,7610,5369
A2M-AS1,131,111,65,168,129,160,204,154,159,136,...,112,138,134,101,135,163,141,148,133,93

In [21]:
counts = counts.transpose()

In [25]:
# raw 저장
# metadata.to_csv('./GSE111016_metadata.csv', sep='\t')
# counts.to_csv('./GSE111016_counts.csv', sep='\t')

## Ensembl to Symbol (by sambomics)

In [57]:
# # sanbomics.tools의 id_map 모듈을 활용하여 매핑할 수 있습니다. 
# mapper = id_map(species = 'human', key = 'ensembl', target = 'symbol')

In [58]:
# # counts 데이터프레임의 Index를 gene symbol로 바꿔줍니다.
# counts['Symbol'] = counts.index.map(mapper.mapper)
# counts.head()

,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 7,Sample 8,Sample 9,Sample 10,...,Sample 32,Sample 33,Sample 34,Sample 35,Sample 36,Sample 37,Sample 38,Sample 39,Sample 40,Symbol
ENSG00000000003,124,145,61,110,122,120,145,118,108,125,...,119,79,67,134,114,106,128,149,122,TSPAN6
ENSG00000000005,7,6,10,16,124,9,37,3,6,45,...,3,6,35,5,16,8,6,27,18,TNMD
ENSG00000000419,536,839,415,690,825,852,774,838,629,708,...,739,639,462,780,551,576,788,742,656,DPM1
ENSG00000000457,402,538,244,486,538,549,629,525,430,453,...,405,431,292,494,443,395,551,483,438,SCYL3
ENSG00000000460,141,119,73,169,96,104,145,115,94,131,...,104,145,85,131,115,141,121,125,120,C1orf112

In [59]:
# # 몇 개의 유전자가 매핑되었는지 확인해봅니다.
# print(f'The shape of counts Dataframe: {counts.shape}')
# counts['Symbol'].isnull().value_counts()

The shape of counts Dataframe: (65217, 41)

False    51332
True     13885
Name: Symbol, dtype: int64

## Filtering genes

In [29]:
counts = counts.T

In [30]:
# 전체 샘플에서 발현량이 없는 유전자를 필터링합니다.
print(f'필터링 전 테이블: {counts.shape}')
counts = counts[counts.sum(axis=1)>0]
print(f'필터링 후 테이블: {counts.shape}')

필터링 전 테이블: (40063, 40)
필터링 후 테이블: (36678, 40)

In [31]:
# 논문 상 필터링 기준
counts = counts[counts.mean(axis=1)>20]
print(f'논문기반 필터링 후 테이블: {counts.shape}')

논문기반 필터링 후 테이블: (15357, 40)

In [32]:
counts = counts.transpose()
counts.head()

GeneSymbol,A2M,A2M-AS1,A2ML1,A4GALT,AAAS,AACS,AADAT,AAGAB,AAK1,AAMDC,...,ZUP1,ZW10,ZWILCH,ZXDA,ZXDB,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
Sample 1,7145,131,5,186,593,172,103,724,1792,1607,...,118,682,96,346,394,1877,15055,573,3175,1338
Sample 2,9004,111,16,177,592,253,93,912,2333,2208,...,194,753,101,418,413,1866,17429,634,3038,1454
Sample 3,3427,65,160,85,330,154,44,434,1488,1042,...,66,329,61,187,196,777,7547,233,1429,642
Sample 4,6806,168,6,161,582,149,91,880,1963,1623,...,144,796,105,331,422,1828,11336,581,2653,1643
Sample 5,6684,129,8,307,559,248,91,917,2257,1558,...,181,665,133,380,407,1762,16293,527,3087,1734

In [33]:
# counts.to_csv('./GSE111016_counts_filtered.csv', sep='\t')

# DEG analysis

In [2]:
# raw 읽어오기
metadata = pd.read_csv('./GSE111016_metadata.csv', sep='\t', index_col=[0])
counts = pd.read_csv('./GSE111016_counts_filtered.csv', sep='\t', index_col=[0], low_memory=False)

In [8]:
def my_deseq(metadata, counts, name):
    # 1. Build DeseqDataSet
    dds = DeseqDataSet(counts=counts,
                       metadata=metadata,
                       design_factors="Condition",
                       refit_cooks=True)
    
    # 2. Run DEseq2
    dds.deseq2()
    
    # 3. Deseq2Stat # 1:'os', 2:'oh'
    group1 = dds.obs.Condition.unique()[1] # 1: 'os'
    group2 = dds.obs.Condition.unique()[0] # 0: 'oh'
    print(f"comparison between {group1} and {group2}")
    
    stat_res = DeseqStats(dds, contrast=('Condition', group1, group2))
    stat_res.summary()
    res = stat_res.results_df

    # 4. Save dds and res as pickle and csv, respectively
    with open(f"./{name.split('_')[1]}/results_{name}_dds.pkl", 'wb') as f:
        pickle.dump(dds, f)
    res.to_csv(f"./{name.split('_')[1]}/results_{name}.csv")

In [9]:
my_deseq(metadata, counts, 'GSE111016_osoh_filtered_refit')

Fitting size factors...
... done in 0.03 seconds.

Fitting dispersions...
... done in 5.10 seconds.

Fitting dispersion trend curve...
... done in 0.57 seconds.

Fitting MAP dispersions...
... done in 6.01 seconds.

Fitting LFCs...
... done in 2.33 seconds.

Replacing 82 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...

comparison between OS and OH

... done in 0.98 seconds.

Log2 fold change & Wald test p-value: Condition OS vs OH
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
A2M       6659.963434       -0.188394  0.083747 -2.249562  0.024477  0.214547
A2M-AS1    123.823629       -0.001157  0.084789 -0.013645  0.989113       NaN
A2ML1       11.030964        0.395696  0.426042  0.928772  0.353007       NaN
A4GALT     206.737365        0.161064  0.106277  1.515517  0.129642       NaN
AAAS       562.242181        0.032603  0.043561  0.748452  0.454188  0.743050
...               ...             ...       ...       ...       ...       ...
ZXDC      1664.379073        0.114611  0.047863  2.394569  0.016640  0.188466
ZYG11B   13204.512796       -0.136301  0.060581 -2.249909  0.024455  0.214547
ZYX        596.301319        0.147968  0.098065  1.508877  0.131330  0.448803
ZZEF1     2829.319141        0.093573  0.040800  2.293480  0.021820  0.207952
ZZZ3      1333.699151        0.016783  0.043503  0.385785  0.699656  0.879382

[15357 rows x 6 columns]

# GSEA
* (코멘트) gsea html 파일이 나옴! gmt, tms, gct 파일 input
* GO에 대한 유전자 score에 따른 정보 나옴

In [ ]:
res.head()
res['Symbol'] = res.index

In [ ]:
ranking = res[['Symbol','stat']].dropna().sort_values('stat', ascending=False)
ranking = ranking.drop_duplicates('Symbol')
ranking

In [ ]:
manual_set = {'things':['COL19A1', 'H19', 'FGF7', 'NHLH2', 'MT2A']}

In [ ]:
del ranking['Symbol']

In [ ]:
pre_res = gp.prerank(rnk = ranking,
                     gene_sets = ['GO_Biological_Process_2021', manual_set],
                     seed = 6, permutation_num = 100)

In [ ]:
out = []

for term in list(pre_res.results):
    out.append([term,
               pre_res.results[term]['fdr'],
               pre_res.results[term]['es'],
               pre_res.results[term]['nes']])

out_df = pd.DataFrame(out, columns = ['Term','fdr', 'es', 'nes']).sort_values('fdr').reset_index(drop = True)
out_df

In [ ]:
print(out_df.sort_values('nes').iloc[0].Term)
print(out_df.sort_values('nes').iloc[1].Term)

In [ ]:
my_term = out_df.sort_values('nes').iloc[0].Term
my_term

In [ ]:
gseaplot(rank_metric=pre_res.ranking, term=my_term, **pre_res.results[my_term])